### PR TITLE
Copy some theory from coq-community/topology

### PR DESCRIPTION
**Pull request by Columbus240**
Related to coq-community/topology#14.

### CODE REVIEW

**Comment by stop-cran** [comment]
@palmskog I see I have permissions here. Have you added me as a co-maintainer, so I can merge this PR?

**Comment by palmskog** [comment]
@stop-cran yes, you are both admins of this project and Topology now. I will open some issue soon in the Topology repo about the previously discussed merging of the repos (but hopefully not the packages).

**Comment by Zimmi48** [comment]
I've fixed the description of the repo to list the three maintainers, but the `meta.yml` and (auto-generated) `README.md` should be fixed as well.

**Comment by Columbus240** [comment]
Thanks for mentioning that `README.md` is generated by `meta.yml`. I didn’t notice that before. I updated both files.

**Pull request merged**
